### ISSUE TITLE
Many tools (i.e. Exiftool) not running, with latest release.

### ISSUE THREAD

**Issue by kirk-marple** [harvard-lts/fits#114]
I was testing out FITS on an MP4 file, but many of the tools aren't getting executed, including Exiftool.

The tool exists here:
fits-1.0.1\tools\exiftool\windows\exiftool.exe

Any ideas on what's missing?  I simply downloaded the latest zip, and ran it from that folder (fits -i foo.mp4).

```
  <statistics fitsExecutionTime="874">
    <tool toolname="MediaInfo" toolversion="0.7.75" executionTime="718" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run
" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.1.5" executionTime="250" />
    <tool toolname="Jhove" toolversion="1.11" status="did not run" />
    <tool toolname="file utility" toolversion="5.03" executionTime="766" />
    <tool toolname="Exiftool" toolversion="10.00" status="did not run" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not
 run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="281"
/>
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="624" />
    <tool toolname="Tika" toolversion="1.10" status="did not run" />
  </statistics>
</fits>
```

**Comment by dbirtwellharvard** [comment]
FITS supports video files only using the MediaInfo Tool with the standard output of Ebucore. This is by design. The MediaInfo tool is the only tool we found which could be used to generate the best metadata for our uses. If you turn on other tools for video metadata generation, you will not get the complete video metadata.

If you really want to use other tools, you do so at your own risk, as only video metadata extraction using MediaInfo has been tested and is officially supported. 

Also note that video is only supported out-of-the-box with 64-bit Java runtimes and the following 64-bit OSes ... Windows 7, Mac OS X, and CentOS. Ubuntu 64 can easily be dropped in as well.

Please see:

http://projects.iq.harvard.edu/fits/fitsfaq

and search for the "Video Support Details" section.

Thanks,

Dave B.

**Comment by kirk-marple** [comment]
Makes sense, thanks.  Just saw all the 'did not run' reports and thought something was missing.
