### ISSUE TITLE
No filestatus data for TIFFs: FITS version 1.0.7 using JHOVE 1.16

### ISSUE THREAD

**Issue by jlderidder** [harvard-lts/fits#132]
Testing FITS 1.0.7 on TIFF files on Windows 10, I am unable to obtain any filestatus information; that XML section is empty, even for TIFFs that are valid and well-formed when tested using FITS 0.8.4 (JHOVE 1.5).  
Example from output:  "  &lt;filestatus /&gt;"
Looking at the JHOVE documentation, it looks as though the TIFF-hul module must be specified with the 
-m flag in order to obtain filestatus information.  Perhaps this is not included in the FITS wrapper?  If not, please advise how best to modify the code to include this -- or any workaround you would recommend.
Thanks!

**Comment by andreagoethals** [comment]
Hi,

Some of the tools FITS embeds extract technical metadata from files (e.g. JHOVE & ExifTool), but some of the tools only identify the format (e.g. DROID, File utility). Its expected behavior that you will not get any format-specific technical metadata when the tool(s) that contributed to identifying the format of your file do not extract metadata from the file. My guess is that the particular flavor of TIFF you have is being identified by one (or more) of the tools that only identify the format. The output should tell you which tools contributed to identifying the format so you can verify this.

Having said that FITS is very configurable so you can make changes to the configuration to turn off and on tools to get it to do what you want.

Hope this helps.
Andrea


—
Andrea Goethals
Manager of Digital Preservation and Repository Services
Harvard Library

**Comment by jlderidder** [comment]
Sorry, Andrea, I guess I wasn't clear.

I want to update from the 0.8.4 version of FITS that we are using, which
*does* provide a filestatus section when testing fits, such as:
  <filestatus>
    <well-formed toolname="Jhove" toolversion="1.5"
status="SINGLE_RESULT">true</well-formed>
    <valid toolname="Jhove" toolversion="1.5"
status="SINGLE_RESULT">true</valid>
  </filestatus>

When I test the very same TIFF file (that was used to generate the above
output) using the 1.0.7 version of FITS, I get the following:
<filestatus />   (no information)

I have set up the FITS the same way as I did before.
How should I configure it differently?

Thank you!

--jody

**Comment by andreagoethals** [comment]
Hi Jody,

With each iteration of FITS, we are trying to improve the accuracy and specificity of the format and technical metadata. It’s expected that you will get different results with different versions of FITS, especially for formats that have many variations (like TIFF or PDF). For example, running the same file against an old version of FITS might tell you it’s a TIFF and output very little technical metadata, and a new version of FITS might tell you it’s a TIFF EXIF and output many technical metadata elements.

JHOVE is the only tool embedded in FITS that can report whether it thinks a file is well-formed and valid (for some formats). FITS has 3 different possible output forms (see http://projects.iq.harvard.edu/fits/understanding-output ). When you are looking at the first 2 types of output (FITS XML and standard), it is outputting summary metadata that has been consolidated by comparing the native tool output of all the tools that have run against that file. This means that if you are looking at this summarized output and do not see those elements output by JHOVE related to validity and well-formedness, JHOVE must not have been one of the tools that was able to come up with the most specific format identification for that file.

But, you can always output the third output form described on the page referenced above (native tool output). This way you can always see, for example, what JHOVE said about the validity and well-formedness. You can also see this way what each tool individually said about the file. I always look at this native tool output when I am trying to troubleshoot why I got a result I didn’t expect. By default, the native tool output is disabled (because it tends to be lengthy). You can enable it through the main FTIS configuration file (fits.xml). See the display-tool-output element described at http://projects.iq.harvard.edu/fits/fits-configuration-files#fits_xml_config All you do is edit that file and change the value for that element to true. Then re-run FITS and you will see the full output.

Hope this helps.

Andrea

**Comment by jlderidder** [comment]
Andrea, thank you so much!
--jody
