### ISSUE TITLE
FITS 1.2.0 crashes if examining the chaiOS HTML file.

### ISSUE THREAD

**Issue by fungunga** [harvard-lts/fits#167]
Examining the "ChaiOS" HTML file leads to a TikaTool ERROR, the FITS does not terminate either. Just execute

$./fits.sh -i ~/chaiOS

and get

2018-02-28 19:31:39 - ERROR - ToolBase:271 - Caught exception running tool: TikaTool
edu.harvard.hul.ois.fits.exceptions.FitsToolException: Exception reading metadata (Error on line 1: Character reference "&#55356" is an invalid XML character.)
	at edu.harvard.hul.ois.fits.tools.tika.TikaTool.buildRawData(TikaTool.java:525)
	at edu.harvard.hul.ois.fits.tools.tika.TikaTool.extractInfo(TikaTool.java:448)
	at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:268)
	at java.lang.Thread.run(Thread.java:748)

[chaiOS.zip](https://github.com/harvard-lts/fits/files/1768401/chaiOS.zip)

Don't know if it is a Tika problem or something else, but I suppose FITS should terminate with an error, and not be stuck in the process.

**Comment by daveneiman** [comment]
Looks like the JDom SAXBuilder class is failing due to invalid characters in the Tika tool. However, the file did process successfully in FITS 1.2.0. Since the input file is > 12MB it took a while to process yet did complete with metadata output from tools other than Tika. I'd suggest turning off tool output in the fits.xml file since the tool output for this input file is quite large.:
<display-tool-output>false</display-tool-output>

**Comment by fungunga** [comment]
You're right! Takes about half a minute here! I was too impatient, as always :-) Sorry, seems to be just another timeout problem at my side! :-) Another issue to close!
