### ISSUE TITLE
File validation inconsistent

### ISSUE THREAD

**Issue by kidon0011** [harvard-lts/fits#190]
I tested several TIFF files in fits 1.4.0 and received a file status for some, but not others. I then used stand alone JHOVE against all of those files and was returned with consistent well-formed and valid messages. 

I am using the following command: fits.bat -i file.tif -xc -o file.txt

**Comment by daveneiman** [comment]
Hello,
It would be helpful if you sent some FITS output -- one where you get the desired output and one where you do not. Please turn on tool output by adjusting the following setting in your fits.xml configuration file before running the processing each of these files.

		<display-tool-output>true</display-tool-output>

The default value is 'false' so you'll need to change that.
This should result in a stanza in each XML output file  of the following:
<toolOutput>
     (tool output here)
</toolOutput>

Attach the output files to your next response.
Thanks!

**Comment by kidon0011** [comment]
[noFileStatus.txt](https://github.com/harvard-lts/fits/files/3031144/noFileStatus.txt)
[fileStatus.txt](https://github.com/harvard-lts/fits/files/3031145/fileStatus.txt)
[jhove.txt](https://github.com/harvard-lts/fits/files/3031147/jhove.txt)

Thanks for the reply. The 'noFileStatus.txt' and 'jhove.txt' attachments are from the same TIFF file, but the former is run with fits and the latter with jhove.

The 'fileStatus.txt' is from a TIFF that did return a file status using fits.

**Comment by daveneiman** [comment]
Thanks for sending the files. I can see what's happening.
In looking at the top of the noFileStatus.txt (really this is an XML file) in the `<identification>` section you can see that the enclosed `<identity>` element shows the format as "TIFF EXIF" as identified by Exiftool, which is another tool used within FITS along with JHOVE as well as several others. "TIFF EXIF" is considered more specific than just "TIFF", which JHOVE did identify. When a more specific tool within FITS identifies a more specific format, the metadata is dropped of those tools within FITS that identify a less specific format. You can see this hierarchy of file formats in the file fits_format_tree.xml within the 'xml' directory. Right in the top section you'll see that "TIFF EXIF" is embedded within the "Tagged Image File Format" element.

In the fileStatus.txt output, there is actually a conflict as noted in the 
`<identification status="CONFLICT">` section. FITS was unable to specifically identify TIFF from the JHOVE tool output. So, even though Exiftool identified "TIFF EXIF", the JHOVE format didn't match in the fits_format_tree.xml file. Thus, there was no format hierarchy eliminating JHOVE as less specific than Exiftool. Since the JHOVE tool appears higher on the lists of tools in fits.xml, its metadata output was used instead of that of Exiftool.

A bit complicated, yes.

However, in the case of both of these files, the FITS output shows metadata generated by Exiftool in noFileStatus.txt and JHOVE in fileStatus.txt.

One thing you might try is to add 'tif' (and possibly tiff) to the list of file extension exclusions in the Exiftool in fits.xml. It would look like this:
`<tool class="edu.harvard.hul.ois.fits.tools.exiftool.Exiftool" exclude-exts="tif,tiff,txt,wps,vsd,jar,avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4" classpath-dirs="lib/exiftool" />`

That way Exiftool won't examine files that end in .tif or .tiff and so you won't get the more specific "TIFF EXIF" output from that tool.

Good luck and please let us know how it works.

**Comment by kidon0011** [comment]
Excluding tif and tiff from the Exifool worked. Thanks for you help!
