### ISSUE TITLE
NLNZ incorrect recognition corrupts result

### ISSUE THREAD

**Issue by johanlundberg92** [harvard-lts/fits#194]
I create a ZIP file with a jpg file inside.
Recognition of this file works fine and delivers SINGLE_RESULT that it is a ZIP file.
However if I rename the file extension to .jpg or .bmp for example SINGLE_RESULT is also delivered but the result is: application/vnd.oasis.opendocument.text.
And the only outputed result on the screen is from NLNZ Metadata Extractor (it seems to take precedence and throw away the result from the other modules).
If I disable NLNZ the result is again correct.
(Running on Windows 10)

**Comment by daveneiman** [comment]
Hello,
I'm curious why you would change the file extension of a ZIP file to something else.
The NLNZ Metadata Extractor tool has not been supported for quite some time. However, for a few file types it still provides some useful metadata. It is under consideration for removal from FITS. However, if you'd like to remove it yourself, it's a simple as commenting-out the NLNZ line in the `<tools>` section of the fits.xml file.

**Comment by johanlundberg92** [comment]
Consider that I am building a file transfer solution and want's to know if this presumably ZIP file really is a ZIP file or if a user just has changed the file extension to try and get around what is allowed to transfer.
Yeah as mentioned I have done testing with commenting it out, just wanted to submit an issue that the result from NLNZ seems to take precedence in some way since it returns SINGLE_RESULT when obviously that should not be the case.....

**Comment by daveneiman** [comment]
In looking into this a bit further here's a bit of an explanation as to what you are seeing:
Within the FITS distribution there is the file `xml/fits_format_tree.xml`. When a ZIP file is processes (with a .zip extension) the identified format "ZIP Format" is found within this file by multiple tools within FITS. For some reason, when renaming the file extension to .jpg or .bmp, the NLNZ tool identifies the file as "application/vnd.oasis.opendocument.text" with a format name of "OpenDocument Text". The element `<branch format="OpenDocument Text"/>` in `xml/fits_format_tree.xml` is a sub-element of `<branch format="ZIP Format">` so is considered more specific. As a result, only the metadata associated with the more specific identification is used in the output. Since only NLNZ tool identified a more specific type, only its metadata is used. I hope this helps to clarify things.

**Comment by johanlundberg92** [comment]
Ahh I see.
Then I guess it is the expected result, thanks for the answer!
