### ISSUE TITLE
Corrupted tiff file recognized as image/tiff

### ISSUE THREAD

**Issue by little9** [harvard-lts/fits#197]
With 1.4.1 when I identify a corrupted tiff image (the magic number is wrong): https://github.com/UCLALibrary/californica/blob/master/spec/fixtures/images/corrupted/food.tif
I'm not getting any indication that the file is corrupt. 

When I use ImageMagick's `identify` is returns that the file is corrupted. 

I would expect that FITS would return that the file was either not well-formed or invalid.

**Comment by daveneiman** [comment]
Yes, you are correct that Jhove does not identify the corruption. When tool output is turned on in the FITS configuration file, fits.xml, Jhove, which is embedded within FITS, shows that the file is 
`<mimeType>application/octet-stream</mimeType>` rather than a TIFF likely because it is corrupt.
Also, in the `<identification>` section Droid shows the identification of two different formats resulting in a conflict. FITS does not incorporate ImageMagick. If anyone would like to attempt this and submit a pull request it would much appreciated.

The full FITS output file is attached. (It is a .txt file since .xml files are disallowed by GitHub. Please change the file extension once downloading.)

[food.tif.fits.txt](https://github.com/harvard-lts/fits/files/3159356/food.tif.fits.txt)

**Comment by little9** [comment]
Thanks for your response! The Samvera code I was looking at was using the application/octet-stream mime type to check for corruption, but was using a much older version of FITS that we upgraded to the current release. I assume that the samvera/hydra code isn't looking in the right spot in the XML anymore to get a mime type so this is on my end somewhere.
