### ISSUE TITLE
Set up GH-pages for FITS

### ISSUE THREAD

**Issue by awoods** [harvard-lts/fits#254]
This task is to [setup GH-pages](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll) in the FITS project (with a temporary theme, or no theme).

**Comment by mferrarini** [comment]
Developers manual is now in the wiki of the FITS repo: https://github.com/harvard-lts/fits/wiki/Developer-Manual. 

All other content is in github pages: https://harvard-lts.github.io/fits/.

Homepage is still in progress and needs to be fleshed out more so that a new user visiting this page knows what FITS can do for them.

**Comment by awoods** [comment]
Resolved with:
- https://harvard-lts.github.io/fits/ and
- https://github.com/harvard-lts/fits/wiki/Developer-Manual
