### ISSUE TITLE
FITS Service

### ISSUE THREAD

**Issue by DaveSiegel** [harvard-lts/fits#26]
I've started work on making FITS run as a service under a Tomcat instance. I welcome any comments about this.

**Comment by dchandekstark** [comment]
:+1:

**Comment by DaveSiegel** [comment]
https://github.com/harvard-lts/FITSservlet

**Comment by fungunga** [comment]
Yeah! Very nice! I finally got this into Puppet today and running, took a while before it got clear to me that I can't submit files to the service :-) I nearly got mad with all the 404's … but I suppose you just can encapsulate all the libs better in the tomcat. I have got all files to inspect on the FITS's machine, where the service is running, too. Thanks for that! Just great!
Just a question: Wouldn't it be faster to use THE FITS directly on the machine, it's installed anyway, and without the servlet? Where exactly is the benefit, if I can't use the service remotely (except the class encapsulation)?

**Comment by daveneiman** [comment]
Thanks for trying out this latest release. Perhaps it should not have been 1.0.0 since it only handles local files. This is why your question of using FITS directly on the machine is valid. In the works is a version of the FITS Service (new "official" name rather than "Fits Servlet") which allows the streaming of an input file via a POST request across the network which would lend greater validity to this project. Stay tuned as there is already a working prototype yet needs to be put into the work pipeline. Would welcome your feedback once that is out.

**Comment by daveneiman** [comment]
The [FITS Service ](https://github.com/harvard-lts/FITSservlet)project now handles both local and remote file upload and processing. Also, there is a complete separation between FITS and FITS Service. In FITS Service (within Tomcat) there is a classpath setting to point to the local FITS deployment. See documentation for details.
