### ISSUE TITLE
JHOVE 1.11 in FITS 0.9

### ISSUE THREAD

**Issue by tulikagupta** [harvard-lts/fits#55]
We downloaded the latest 9.0 and found some of the Jhove 1.5 elements are missing from the Jhove 1.11. For example,

the x/ySamplingFrequency values are captured at the beginning of the FITS
xml:

-
-
... ...
    in.
    400
    400
... ...

However, they are not found in the Jhove 1.11 output as they used to in Jhove
1.5 under mix:SpatialMetrics:

... ...
-
    2
    400
    400
... ...

In addition, the mix:Segments\mix:StripOffsets is not found in Jhove 1.11 either.

Do you know why?

**Comment by daveneiman** [comment]
Yes, in upgrading to Jhove 1.11 we came across many changes to the raw tool output resulting in corresponding changes to the XSLT which processes the tool's output. Many of the output values have been changed from starting with an upper case letter to lower case.

Related to your question, when we process a TIFF file here is a sample of some of the Jhove 1.11 output:
```
                                  <mix:ImageAssessmentMetadata>
                                    <mix:SpatialMetrics>
                                      <mix:samplingFrequencyUnit>in.</mix:samplingFrequencyUnit>
                                      <mix:xSamplingFrequency>
                                        <mix:numerator>7620000</mix:numerator>
                                        <mix:denominator>10000</mix:denominator>
                                      </mix:xSamplingFrequency>
                                      <mix:ySamplingFrequency>
                                        <mix:numerator>7620000</mix:numerator>
                                        <mix:denominator>10000</mix:denominator>
                                      </mix:ySamplingFrequency>
                                    </mix:SpatialMetrics>
                                    <mix:ImageColorEncoding>
                                      <mix:BitsPerSample>
                                        <mix:bitsPerSampleValue>8</mix:bitsPerSampleValue>
                                        <mix:bitsPerSampleValue>8</mix:bitsPerSampleValue>
                                        <mix:bitsPerSampleValue>8</mix:bitsPerSampleValue>
                                        <mix:bitsPerSampleUnit>integer</mix:bitsPerSampleUnit>
                                      </mix:BitsPerSample>
                                      <mix:samplesPerPixel>3</mix:samplesPerPixel>
                                    </mix:ImageColorEncoding>
                                  </mix:ImageAssessmentMetadata>
```
The corresponding output for Jhove 1.5 is this:
```
                                  <mix:ImagingPerformanceAssessment>
                                    <mix:SpatialMetrics>
                                      <mix:SamplingFrequencyUnit>2</mix:SamplingFrequencyUnit>
                                      <mix:XSamplingFrequency>762</mix:XSamplingFrequency>
                                      <mix:YSamplingFrequency>762</mix:YSamplingFrequency>
                                      <mix:ImageWidth>3420</mix:ImageWidth>
                                      <mix:ImageLength>5110</mix:ImageLength>
                                    </mix:SpatialMetrics>
                                    <mix:Energetics>
                                      <mix:BitsPerSample>8,8,8</mix:BitsPerSample>
                                      <mix:SamplesPerPixel>3</mix:SamplesPerPixel>
                                    </mix:Energetics>
                                  </mix:ImagingPerformanceAssessment>
 ```
Note how many of the element values now start with lower case, xSamplingFrequency instead of XSamplingFrequency. Also, note the difference in how BitsPerSample is now elaborated. Also, note how samplingFrequencyUnit is now a alpha value rather than an integer. There are many formerly integer values that, rather than needing to be transformed into their corresponding alpha equivalent, now show the alpha value. I believe this corresponds to the MIX 2.0 schema as noted in the change to the namespace value.
I hope this helps.

**Comment by tulikagupta** [comment]
Makes sense. Can you please explain missing tag mix:Segments\mix:StripOffsets too?

**Comment by daveneiman** [comment]
Sorry, I'm not familiar with that tag and we do not use it. I believe some tags may have been removed from the Jhove upgrade. You would need to consult the Jhove website for more information on that.

**Comment by tulikagupta** [comment]
thanks for prompt response. I have raised this question in Jhove community.
